### ISSUE TITLE
Is celery configuration require?

### ISSUE THREAD

**Issue by padaliyajay** [silverlogic/baseapp-backend#79]
I am using cloudflare-stream-field for my project but sometime i am getting "connection refused" error from celery

So is celery require to configure in my project in order to use cloudflare-stream-field?

I found this documentation on it
https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

**Comment by nossila** [comment]
@padaliyajay yes celery is required, there are some tasks that runs on celery! You can check the [README here](https://github.com/silverlogic/baseapp-backend/tree/master/baseapp-cloudflare-stream-field), its not complete, but as you can see you also need to specify a CELERY_TASK_ROUTES for the tasks in this package.

And sorry for the late response!

**Comment by padaliyajay** [comment]
Thank you for reply.

What if i don't want to use celery. then still cloudflare-stream-field works?

**Comment by padaliyajay** [comment]
I successfully configured celery in my django project and also rabbitmq server running

But i am getting following error on save of admin form

Basic.publish: (404) NOT_FOUND - no exchange 'default' in vhost '/'

I am sure something is related to this

```
CELERY_TASK_ROUTES = {
    "baseapp_cloudflare_stream_field.tasks.refresh_from_cloudflare": {
        "exchange": "default",
        "routing_key": "default",
    },
    "baseapp_cloudflare_stream_field.tasks.generate_download_url": {
        "exchange": "default",
        "routing_key": "default",
    },
}
```

Do i need to replace something with "default"?

**Comment by nossila** [comment]
@padaliyajay yes, you can replace `default` with whatever you have in `CELERY_TASK_QUEUES` or maybe you can delete the whole `CELERY_TASK_ROUTES` and see if it works fine for you, which I think it will... Let me know what your findings please.

**Comment by padaliyajay** [comment]
thank you for reply. i removed it and it still works
